version: "3"

services:
  mysqldb:
    container_name: ums-db
    image: mysql:8.0.29
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3306"

  api:
    depends_on:
      - mysqldb
    container_name: ums-api
    image: ums-api
    build: api/.
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.database-platform" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "validate",
                
        "server.error.include-message" : "always",
        "server.error.include-binding-errors" : "always",
        "server.error.include-stacktrace" : "never",
        "server.error.include-exception" : "true",
                
        "security.jwt.token.secret-key" : "$SPRING_TOKEN_SECRET_KEY",
        "security.jwt.token.jwtExpirationSeconds" : "$SPRING_TOKEN_ACCESS_EXPIRATION_SECONDS",
        "security.jwt.token.jwtRefreshExpirationSeconds" : "$SPRING_TOKEN_REFRESH_EXPIRATION_SECONDS"
      }'

  frontend:
    container_name: ums-ui
    image: ums-ui
    build: frontend/.
    ports:
      - "4200:4200"
    depends_on:
      - api
